version: '3.7'
networks:
  default:
    external: true
    name: traefik_main
services:
  app:
    image: traefik:2.4.8
    restart: unless-stopped
    command:
      - "--log.level=INFO"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_main"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.https.http.tls=true"
      - "--entrypoints.https.http.tls.certresolver=lets_encrypt"
      - "--certificatesresolvers.lets_encrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.lets_encrypt.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.lets_encrypt.acme.storage=/etc/acme.json"
      - "--certificatesresolvers.lets_encrypt.acme.email=${TRAEFIK_LETS_ENCRYPT_EMAIL}"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /opt/compose/volumes/traefik/acme.json:/etc/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
