version: '3.7'
services:
  mongodb:
    image: mongo:4.4.6
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_root_pw
    secrets:
      - mongodb_root_pw
  app:
    image: pritunl/pritunl-zero:1.0.2014.22
    restart: unless-stopped
    networks:
      - default
      - traefik
    links:
      - mongodb
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ID=eb8f28abfe3f7bc0d1709a18
      - MONGO_URI=mongodb://mongodb:27017/pritunl-zero
    labels:
      - traefik.enable=true
      - "traefik.http.routers.pritunl.rule=Host(`${PRITUNL_DOMAIN}`)"
networks:
  traefik:
    external: true
    name: traefik_main
secrets:
  mongodb_root_pw:
    file: ./secrets/mongodb_root_pw.txt 
