version: '3.7'
services:
  # app:
  #   build:
  #     context: .
  #   #image: embarkstudios/wireguard-ui:latest
  #   entrypoint: "/wireguard-ui"
  #   privileged: true
  #   network_mode: "host"
  #   restart: always
  #   # networks:
  #   #   - default
  #   #   - traefik
  #   volumes:
  #     - /opt/compose/volumes/wireguard:/data
  #     # - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - WIREGUARD_UI_LISTEN_ADDRESS=:8080
  #     - WIREGUARD_UI_LOG_LEVEL=debug
  #     - WIREGUARD_UI_DATA_DIR=/data
  #     - WIREGUARD_UI_WG_ENDPOINT=${WIREGUARD_DOMAIN}:51820
  #     - WIREGUARD_UI_CLIENT_IP_RANGE=192.168.10.0/24
  #    # - WIREGUARD_UI_WG_DNS=192.168.10.0
  #     - WIREGUARD_UI_NAT=true
  #     - WIREGUARD_UI_NAT_DEVICE=eth0
  #   # labels:
  #   #   - traefik.enable=true
  #   #   - "traefik.http.routers.nextcloud.rule=Host(`${WIREGUARD_DOMAIN}`)"
# networks:
#   traefik:
#     external: true
#     name: traefik_main
app:
  image: adrum/wireguard-ui
  container_name: wireguard-ui
  privileged: true
  cap_add:
    - NET_ADMIN
    - SYS_MODULE
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    - WIREGUARD_UI_LISTEN_ADDRESS=:8080
    - WIREGUARD_UI_LOG_LEVEL=debug
    - WIREGUARD_UI_DATA_DIR=/data
    - WIREGUARD_UI_WG_ENDPOINT=your-endpoint-address:51820
    - WIREGUARD_UI_CLIENT_IP_RANGE=192.168.10.0/24
    - WIREGUARD_UI_WG_DNS=1.1.1.1
    - WIREGUARD_UI_NAT=true
    - WIREGUARD_UI_NAT_DEVICE=eth0
  volumes:
    - ./data:/data
    - /lib/modules:/lib/modules
  network_mode: "host"
  sysctls:
    - net.ipv4.conf.all.src_valid_mark=1
  restart: unless-stopped
